version: 0.2

env:
  shell: bash
  exported-variables:
    - BSS_IMAGE_ASSET_REPOSITORY_NAME
    - BUILD_VERSION
    - CN_ASSETS
    - GLOBAL_ASSETS
    - ECR_REPOS
    - CN_ECR_REPOS
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - |-
        set -euxo pipefail
        FEATURE_NAME="${FEATURE_NAME:-''}"
        export BSS_IMAGE_ASSET_REPOSITORY_NAME=$(echo "$SOLUTION_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
        BUILD_VERSION=$(git -c pager.tag=false tag --points-at $(git rev-parse --short HEAD) | tail -1)
        if [ "$BUILD_VERSION" == '' ]; then
          BUILD_VERSION=latest
        fi
        if [ "$FEATURE_NAME" != '' ]; then
          BUILD_VERSION=$BUILD_VERSION-$FEATURE_NAME
        fi

        export BUILD_VERSION=${BUILD_VERSION}-$(/bin/date +"%Y%m%d%H%M")-$(git rev-parse --short HEAD)
        export GLOBAL_ASSETS='default/'
        export CN_ASSETS='cn/'
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/deployment/build-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${BUILD_VERSION}
      - mkdir -p deployment/open-source/ && touch deployment/open-source/.empty
  post_build:
    commands:
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec.yml || true
      - |-
        set -euxo pipefail
        __dir="${CODEBUILD_SRC_DIR}/deployment"
        function join_by { local IFS="$1"; shift; echo "$*"; }
        export ECR_REPOS=$(join_by , `cat "${__dir}/ecr-repos"`)
artifacts:
  files:
    - .git/**/*
    - deployment/**/*
    - docs/**/*
    - buildspec.yml
    - CHANGELOG.md
    - .cfnnag_*
